services:
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - ENV=production
    env_file:
      - ./.env
    command: ["python3.12", "-m", "ci_agent.main"]
